import { createClient } from '@supabase/supabase-js';
import { icons } from './icons.js';
import './admin.css';
const rawUrl=String(import.meta.env.VITE_SUPABASE_URL||'').trim();
const url=rawUrl.replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');
const key=String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'').trim();
const app=document.querySelector('#admin-app');
const sb=url&&key?createClient(url,key):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let products=[];let categories=[];let user=null;let profile=null;
function errorText(e){return e?.message||e?.error_description||'Não foi possível concluir a solicitação.'}
function layout(body){return `<header><a class="brand" href="/"><img src="/logo.svg" alt="Rooblox"></a><div class="head-right"><a href="/">Ver loja</a><button id="signout">Sair</button></div></header><main>${body}</main>`}
function login(msg=''){app.innerHTML=`<section class="auth"><div class="auth-card"><img src="/logo.svg" alt="Rooblox"><span>ADMINISTRAÇÃO</span><h1>Painel Rooblox</h1><p>Acesso restrito à equipe autorizada.</p>${msg?`<div class="error">${esc(msg)}</div>`:''}<form id="admin-login"><label>E-mail<input name="email" type="email" autocomplete="username" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label><button>Entrar no painel</button></form></div></section>`;document.querySelector('#admin-login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)return login(errorText(error));await boot()}}
async function isAdmin(){if(!user)return false;const {data,error}=await sb.from('profiles').select('id,display_name,username,role').eq('id',user.id).maybeSingle();if(error)throw error;profile=data;return ['LIDER','ADMIN','ADMINISTRADOR','OWNER'].includes(String(data?.role||'').toUpperCase())}
async function loadData(){const [p,c]=await Promise.all([sb.from('products').select('*').order('created_at',{ascending:false}),sb.from('store_categories').select('*').order('sort_order')]);if(p.error)throw p.error;if(c.error)throw c.error;products=p.data||[];categories=c.data||[]}
function dashboard(){const active=products.filter(p=>p.active!==false);const stock=products.reduce((n,p)=>n+Number(p.stock_quantity||0),0);app.innerHTML=layout(`<div class="admin-shell"><aside><div class="admin-title">${icons.grid}<span>Administração</span></div><button class="nav active" data-tab="dashboard">${icons.grid}<span>Visão geral</span></button><button class="nav" data-tab="products">${icons.box}<span>Produtos</span></button><button class="nav" data-tab="categories">${icons.game}<span>Categorias</span></button><button class="nav" data-tab="orders">${icons.orders}<span>Pedidos</span></button><button class="nav" data-tab="users">${icons.user}<span>Usuários</span></button></aside><section class="content"><div class="top"><div><small>ROOBLOX / ADMIN</small><h1>Olá, ${esc(profile?.display_name||profile?.username||'Administrador')}</h1><p>Gerencie produtos, estoque e a operação da loja.</p></div><button class="primary" id="new-product">${icons.box}<span>Novo produto</span></button></div><div class="stats"><article><span>Produtos ativos</span><b>${active.length}</b></article><article><span>Itens em estoque</span><b>${stock}</b></article><article><span>Categorias</span><b>${categories.length}</b></article><article><span>Acesso</span><b>${esc(profile?.role||'ADMIN')}</b></article></div><div id="panel"><div class="section-card"><div class="section-head"><div><h2>Produtos recentes</h2><p>Edite preços, imagens, estoque e disponibilidade.</p></div><button class="secondary" id="refresh">Atualizar</button></div><div class="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Status</th><th></th></tr></thead><tbody>${products.slice(0,12).map(row).join('')||'<tr><td colspan="6" class="empty">Nenhum produto cadastrado.</td></tr>'}</tbody></table></div></div></div></section></div>`);bindDashboard()}
function row(p){return `<tr><td><div class="prod"><div class="thumb">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:icons.box}</div><div><b>${esc(p.name)}</b><small>${esc(p.delivery_type||'digital')}</small></div></div></td><td>${esc(p.category_slug||'—')}</td><td>${money(p.price)}</td><td>${Number(p.stock_quantity||0)}</td><td><span class="status ${p.active===false?'off':''}">${p.active===false?'Inativo':'Ativo'}</span></td><td><button class="edit" data-edit="${esc(p.id)}">Editar</button></td></tr>`}
function bindDashboard(){document.querySelector('#signout').onclick=async()=>{await sb.auth.signOut();location.reload()};document.querySelector('#new-product').onclick=()=>openProduct();document.querySelector('#refresh').onclick=async()=>{await loadData();dashboard()};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{if(b.dataset.tab==='products')productsPage();else if(b.dataset.tab==='categories')categoriesPage();else if(b.dataset.tab==='orders')simplePage('Pedidos','Os pedidos e pagamentos serão exibidos aqui após a confirmação pelo backend.');else if(b.dataset.tab==='users')simplePage('Usuários','A gestão de usuários deve permanecer protegida por RLS e permissões administrativas.');else dashboard()})}
function openProduct(id){const p=products.find(x=>x.id===id)||{};app.insertAdjacentHTML('beforeend',`<div class="modal"><form id="product-form" class="modal-card"><button type="button" class="close" id="close">×</button><span>CATÁLOGO</span><h2>${id?'Editar produto':'Novo produto'}</h2><label>Nome<input name="name" required maxlength="120" value="${esc(p.name)}"></label><label>Descrição<textarea name="description" maxlength="2000">${esc(p.description)}</textarea></label><div class="two"><label>Preço<input name="price" type="number" min="0" step="0.01" required value="${esc(p.price??0)}"></label><label>Estoque<input name="stock_quantity" type="number" min="0" step="1" required value="${esc(p.stock_quantity??0)}"></label></div><label>Categoria<select name="category_slug"><option value="">Sem categoria</option>${categories.map(c=>`<option value="${esc(c.slug)}" ${p.category_slug===c.slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Imagem — URL segura<input name="image_url" type="url" placeholder="https://..." value="${esc(p.image_url)}"></label><div class="two"><label>Tipo de entrega<select name="delivery_type"><option value="digital" ${p.delivery_type==='digital'?'selected':''}>Digital</option><option value="manual" ${p.delivery_type==='manual'?'selected':''}>Atendimento</option></select></label><label>Status<select name="active"><option value="true" ${p.active!==false?'selected':''}>Ativo</option><option value="false" ${p.active===false?'selected':''}>Inativo</option></select></label></div><label class="check"><input type="checkbox" name="featured" ${p.featured?'checked':''}> Destacar na loja</label><div class="actions"><button type="button" class="danger" id="delete">Excluir</button><button class="primary">Salvar produto</button></div></form></div>`);const modal=document.querySelector('.modal');document.querySelector('#close').onclick=()=>modal.remove();document.querySelector('#delete').onclick=async()=>{if(!id)return modal.remove();if(!confirm('Excluir este produto?'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)return alert(errorText(error));modal.remove();await loadData();dashboard()};document.querySelector('#product-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const data={name:f.get('name').trim(),description:f.get('description').trim()||null,price:Number(f.get('price')),stock_quantity:Number(f.get('stock_quantity')),category_slug:f.get('category_slug')||null,image_url:f.get('image_url').trim()||null,delivery_type:f.get('delivery_type'),active:f.get('active')==='true',featured:f.get('featured')==='on'};const q=id?sb.from('products').update(data).eq('id',id):sb.from('products').insert(data);const {error}=await q;if(error)return alert(errorText(error));modal.remove();await loadData();dashboard()}}
function productsPage(){dashboard()}
function categoriesPage(){app.innerHTML=layout(`<div class="simple"><div><small>ADMIN / CATÁLOGO</small><h1>Categorias</h1><p>Organize os jogos exibidos na loja.</p></div><div class="section-card"><div class="category-list">${categories.map(c=>`<div><b>${esc(c.name)}</b><span>${esc(c.slug)}</span><span>${c.active===false?'Inativa':'Ativa'}</span></div>`).join('')||'<p>Nenhuma categoria.</p>'}</div></div></div>`);document.querySelector('#signout').onclick=async()=>{await sb.auth.signOut();location.reload()}}
function simplePage(title,text){app.innerHTML=layout(`<div class="simple"><small>ADMIN / OPERAÇÃO</small><h1>${title}</h1><p>${text}</p><div class="section-card"><h2>Área protegida</h2><p>As operações administrativas devem ser executadas pelo backend autorizado e auditadas.</p></div></div>`);document.querySelector('#signout').onclick=async()=>{await sb.auth.signOut();location.reload()}}
async function boot(){if(!sb)return login('Supabase não está configurado. Verifique VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY na Vercel.');const {data,error}=await sb.auth.getSession();if(error)return login(errorText(error));user=data.session?.user;if(!user)return login();try{if(!(await isAdmin()))return login('Esta conta não possui permissão para acessar o painel.');await loadData();dashboard()}catch(e){login(errorText(e))}}
boot();
