import { createClient } from '@supabase/supabase-js';
import './checkout-pro.css';
const url=String(import.meta.env.VITE_SUPABASE_URL||'').trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');
const key=String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'').trim();
const sb=url&&key?createClient(url,key):null; const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let cart=JSON.parse(localStorage.getItem('rooblox_cart')||'[]'),session=null,payment=JSON.parse(sessionStorage.getItem('rooblox_checkout_payment')||'null'),timer=null,submitting=false;
const save=()=>localStorage.setItem('rooblox_cart',JSON.stringify(cart));
function shell(body){return `<section class="checkout-page"><div class="checkout-head"><span class="eyebrow">ROOBLOX • CHECKOUT SEGURO</span><h1>Finalize sua compra</h1><p>Pagamento protegido, pedido salvo na sua conta e acompanhamento em tempo real.</p></div><div class="checkout-steps"><span class="checkout-step active">1 · Pedido</span><span class="checkout-step ${payment?'active':''}">2 · PIX</span><span class="checkout-step">3 · Entrega</span></div>${body}</section>`}
function render(){const total=cart.reduce((n,x)=>n+Number(x.price)*Number(x.quantity),0);app.innerHTML=shell(`<div class="checkout-grid-pro"><section class="checkout-card"><div class="checkout-card-head"><h2>Itens do pedido</h2><p>${cart.length} item(ns) no seu carrinho</p></div>${cart.length?cart.map((x,i)=>`<div class="checkout-item"><div class="checkout-item-img">${x.image_url?`<img src="${esc(x.image_url)}" alt="" style="width:100%;height:100%;object-fit:cover;border-radius:14px">`:'◈'}</div><div><div class="checkout-item-name">${esc(x.name)}</div><span class="checkout-item-meta">Quantidade: ${x.quantity} · Entrega: ${esc(x.delivery_type||'digital')}</span></div><div><b>${brl(Number(x.price)*Number(x.quantity))}</b><br><button class="checkout-remove" data-remove="${i}">Remover</button></div></div>`).join(''):`<div class="checkout-alert" style="margin:22px">Seu carrinho está vazio. <a href="/#/catalogo">Voltar ao catálogo</a></div>`}<div class="checkout-safe" style="padding:18px 22px"><div>✓ Pedido vinculado à sua conta</div><div>✓ PIX processado pelo gateway configurado</div><div>✓ Status acompanhado automaticamente</div></div></section><aside class="checkout-card checkout-summary"><div class="checkout-card-head"><h2>Pagamento</h2><p>PIX instantâneo</p></div>${payment?paymentView(payment):formView(total)}</aside></div>`);
document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);save();render()});document.querySelector('#generate')?.addEventListener('click',generate);document.querySelector('#copy')?.addEventListener('click',copyPix)}
function formView(total){if(!session)return `<div class="checkout-summary"><div class="checkout-alert">Entre na sua conta para continuar. Seu carrinho permanecerá salvo.</div><a class="checkout-generate" style="display:block;text-align:center;text-decoration:none" href="/#/login">Entrar na conta</a></div>`;return `<div class="checkout-summary"><div class="checkout-input"><label>Nome do pagador</label><input id="payerName" maxlength="120" value="${esc(session.user.user_metadata?.display_name||'')}" placeholder="Seu nome completo"></div><div class="checkout-input"><label>CPF <span style="color:var(--rx-muted)">obrigatório para o PIX</span></label><input id="cpf" inputmode="numeric" maxlength="14" placeholder="000.000.000-00"></div><div class="checkout-total"><span>Total</span><strong>${brl(total)}</strong></div><label class="checkout-terms"><input id="terms" type="checkbox"> <span>Concordo com os <a href="/#/termos">Termos de Uso</a> e a <a href="/#/reembolso">Política de Reembolso</a>.</span></label><button id="generate" class="checkout-generate" ${cart.length?'':'disabled'}>Gerar pagamento PIX</button><div id="err" class="checkout-alert" style="display:none"></div><div class="checkout-safe"><div>🔒 Seus dados são transmitidos com segurança.</div><div>⚡ PIX com confirmação automática.</div></div></div>`}
function paymentView(p){const qr=p.qrCodeBase64?(String(p.qrCodeBase64).startsWith('data:')?p.qrCodeBase64:`data:image/png;base64,${p.qrCodeBase64}`):p.qrcodeUrl;const s=String(p.status||'pending').toLowerCase();return `<div class="pix-result"><div class="pix-state"><span>●</span><div><b>${['paid','processing','completed','delivered'].includes(s)?'Pagamento confirmado':'Aguardando pagamento'}</b><span>Pedido ${esc(String(p.orderId||'').slice(0,8))} · você pode fechar esta página.</span></div></div>${qr?`<img src="${esc(qr)}" alt="QR Code PIX">`:''}${p.copyPaste?`<div style="text-align:left"><small>PIX copia e cola</small><div class="pix-copy"><input id="copycode" readonly value="${esc(p.copyPaste)}"><button id="copy">Copiar</button></div></div>`:''}<div class="payment-timeline"><div class="on">✓ PIX gerado</div><div class="${['paid','processing','completed','delivered'].includes(s)?'on':''}">○ Pagamento confirmado</div><div class="${['completed','delivered'].includes(s)?'on':''}">○ Pedido processado/entregue</div></div><div id="payment-status" class="checkout-alert">Status atual: ${esc(p.status||'PENDENTE')}</div><a href="/orders.html" style="display:block;margin-top:14px">Acompanhar em Meus pedidos →</a></div>`}
async function errText(e){try{const r=e?.context;if(r?.json){const b=await r.json();return b?.gateway_message||b?.message||b?.error||JSON.stringify(b)}if(r?.text)return await r.text()}catch{}return e?.message||'Não foi possível processar o pagamento.'}
function validCpf(v){const d=String(v||'').replace(/\D/g,'');if(d.length!==11||/^([0-9])\1+$/.test(d))return false;let s=0;for(let i=0;i<9;i++)s+=Number(d[i])*(10-i);let x=(s*10)%11;if(x===10)x=0;if(x!==Number(d[9]))return false;s=0;for(let i=0;i<10;i++)s+=Number(d[i])*(11-i);x=(s*10)%11;if(x===10)x=0;return x===Number(d[10])}async function generate(){if(submitting)return;const box=document.querySelector('#err');box.style.display='block';box.textContent='Validando dados e gerando seu PIX…';const cpf=document.querySelector('#cpf').value.replace(/\D/g,'');const name=document.querySelector('#payerName').value.trim();if(!validCpf(cpf)){box.textContent='Informe um CPF válido.';return}if(!name){box.textContent='Informe o nome do pagador.';return}if(!document.querySelector('#terms')?.checked){box.textContent='Aceite os termos para continuar.';return}submitting=true;const btn=document.querySelector('#generate');if(btn){btn.disabled=true;btn.textContent='Gerando PIX…'}const {data,error}=await sb.functions.invoke('rooblox-checkout-v2',{body:{items:cart,payerName:name,payerDocument:cpf}});if(error){submitting=false;box.textContent=await errText(error);if(btn){btn.disabled=false;btn.textContent='Gerar pagamento PIX'}return}if(data?.error){submitting=false;{box.textContent=data.gateway_message||data.message||String(data.error);return}if(!data?.orderId){submitting=false;box.textContent='O pedido não foi criado. Tente novamente.';if(btn){btn.disabled=false;btn.textContent='Gerar pagamento PIX'}return}payment=data;sessionStorage.setItem('rooblox_checkout_payment',JSON.stringify(payment));render();watchStatus()}
async function watchStatus(){if(timer)clearInterval(timer);if(!payment?.orderId)return;const check=async()=>{const {data}=await sb.from('store_orders').select('id,status,updated_at').eq('id',payment.orderId).maybeSingle();if(!data)return;payment.status=data.status;const s=String(data.status).toLowerCase();if(['paid','processing','completed','delivered'].includes(s)){if(timer)clearInterval(timer);localStorage.removeItem('rooblox_cart');sessionStorage.removeItem('rooblox_checkout_payment');setTimeout(()=>location.href='/orders.html',1800)}else{const el=document.querySelector('#payment-status');if(el)el.textContent='Status atual: '+data.status}};await check();timer=setInterval(check,4000)}
async function copyPix(){const i=document.querySelector('#copycode');if(!i)return;try{await navigator.clipboard.writeText(i.value)}catch{i.select();document.execCommand('copy')}const b=document.querySelector('#copy');if(b){b.textContent='Copiado ✓';setTimeout(()=>b.textContent='Copiar',1500)}}
(async()=>{if(!sb){app.innerHTML=shell('<div class="checkout-alert">Supabase não configurado. Verifique as variáveis de ambiente.</div>');return}const s=await sb.auth.getSession();session=s.data.session;render()})();