import { createClient } from '@supabase/supabase-js';
import './store-pages.css';
const url=String(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');
const key=String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'').trim();
const sb=createClient(url,key); const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let cart=JSON.parse(localStorage.getItem('rooblox_cart')||'[]'),session=null,payment=null,watch=null;
function render(){const total=cart.reduce((n,x)=>n+Number(x.price)*Number(x.quantity),0);app.innerHTML=`<section class="checkout-page"><div class="checkout-head"><span class="eyebrow">ROOBLOX • CHECKOUT</span><h1>Finalizar compra</h1><p>Seu pedido ficará salvo na sua conta mesmo se você sair desta página.</p></div><div class="checkout-grid"><section class="panel"><h2>Seu pedido</h2>${cart.length?cart.map((x,i)=>`<div class="order-line"><div><b>${esc(x.name)}</b><small>Quantidade: ${x.quantity} • ${x.accountIds?.length?'Conta selecionada':'Atendimento'}</small></div><strong>${brl(x.price*x.quantity)}</strong><button data-remove="${i}" aria-label="Remover">×</button></div>`).join(''):'<div class="notice">Seu carrinho está vazio.</div>'}<div class="total"><span>Total</span><b>${brl(total)}</b></div></section><section class="panel payment"><h2>Pagamento PIX</h2>${!session?'<div class="notice">Entre na sua conta para continuar.</div>':payment?paymentView(payment):`<label>Nome do pagador<input id="payerName" value="${esc(session.user.user_metadata?.display_name||session.user.email||'')}" maxlength="120"></label><label>CPF <small>obrigatório para gerar o PIX</small><input id="cpf" inputmode="numeric" maxlength="14" placeholder="000.000.000-00"></label><button id="generate" class="btn" ${cart.length?'':'disabled'}>Gerar PIX</button><div id="err" class="error"></div>`}</section></div></section>`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);localStorage.setItem('rooblox_cart',JSON.stringify(cart));render()});document.querySelector('#generate')?.addEventListener('click',generate)}
function paymentView(p){const qr=p.qrCodeBase64?(String(p.qrCodeBase64).startsWith('data:')?p.qrCodeBase64:`data:image/png;base64,${p.qrCodeBase64}`):p.qrcodeUrl;return `<div class="payment-status"><span class="status-dot"></span><div><b>PIX aguardando pagamento</b><small>Pedido salvo. Você pode fechar a página e acompanhar em Meus pedidos.</small></div></div>${qr?`<div class="qr"><img src="${esc(qr)}" alt="QR Code PIX"></div>`:'<div class="notice">O gateway não retornou um QR Code.</div>'}<label>PIX copia e cola<div class="copy-row"><input id="copycode" readonly value="${esc(p.copyPaste||'')}"><button id="copy">Copiar</button></div></label><div id="payment-status" class="notice">Status: ${esc(p.status||'PENDENTE')}</div>`}
async function readableFunctionError(error){try{const response=error?.context;if(response?.json){const body=await response.json();return body?.gateway_message||body?.message||body?.error||JSON.stringify(body)}if(response?.text){return await response.text()} }catch{} return error?.message||'Não foi possível gerar o pagamento.'}
async function generate(){const err=document.querySelector('#err');err.textContent='Gerando PIX com segurança…';const payerDocument=document.querySelector('#cpf').value.replace(/\D/g,'');if(payerDocument.length!==11){err.textContent='Informe um CPF válido.';return}const payerName=document.querySelector('#payerName').value.trim();if(!payerName){err.textContent='Informe o nome do pagador.';return}const {data,error}=await sb.functions.invoke('rooblox-checkout-v2',{body:{items:cart,payerName,payerDocument}});if(error){err.textContent=await readableFunctionError(error);return}if(data?.error){err.textContent=data.gateway_message||data.message||String(data.error);return}if(!data?.orderId||(!data.copyPaste&&!data.qrCodeBase64&&!data.qrcodeUrl)){err.textContent='O gateway não retornou os dados do PIX. Tente novamente.';return}payment=data;render();startWatch()}
function startWatch(){if(watch)clearInterval(watch);if(!payment?.orderId)return;watch=setInterval(async()=>{const r=await sb.from('store_orders').select('id,status').eq('id',payment.orderId).maybeSingle();if(r.data){const s=String(r.data.status);const el=document.querySelector('#payment-status');if(el)el.textContent='Status: '+s;if(['paid','processing','completed','delivered'].includes(s.toLowerCase())){clearInterval(watch);localStorage.removeItem('rooblox_cart');const c=await sb.from('product_chats').select('id').eq('order_id',payment.orderId).maybeSingle();setTimeout(()=>{location.href=c.data?.id?'/chat.html?id='+encodeURIComponent(c.data.id):'/orders.html'},700)}}},4000)}
document.addEventListener('click',async e=>{if(e.target.id==='copy'){const i=document.querySelector('#copycode');try{await navigator.clipboard.writeText(i.value);e.target.textContent='Copiado!';setTimeout(()=>e.target.textContent='Copiar',1500)}catch{i.select();document.execCommand('copy')}}});
(async()=>{const s=await sb.auth.getSession();session=s.data.session;render()})();