import { createClient } from '@supabase/supabase-js';
import './checkout-pro.css';

const rawUrl=String(import.meta.env.VITE_SUPABASE_URL||'').trim();
const url=rawUrl.replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');
const key=String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'').trim();
const sb=url&&key?createClient(url,key):null;
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let cart=JSON.parse(localStorage.getItem('rooblox_cart')||'[]');
let payment=JSON.parse(sessionStorage.getItem('rooblox_checkout_payment')||'null');
let session=null,timer=null,busy=false;
const saveCart=()=>localStorage.setItem('rooblox_cart',JSON.stringify(cart));
const validCpf=value=>{const d=String(value||'').replace(/\D/g,'');if(d.length!==11||/^([0-9])\1+$/.test(d))return false;let sum=0;for(let i=0;i<9;i++)sum+=+d[i]*(10-i);let x=(sum*10)%11;if(x===10)x=0;if(x!==+d[9])return false;sum=0;for(let i=0;i<10;i++)sum+=+d[i]*(11-i);x=(sum*10)%11;if(x===10)x=0;return x===+d[10]};
function shell(body){return `<main class="checkout-page"><header class="checkout-head"><div><span class="eyebrow">◈ ROOBLOX · CHECKOUT SEGURO</span><h1>Finalize sua compra</h1><p>Uma experiência rápida, segura e feita para você acompanhar cada etapa do pedido.</p></div></header><nav class="checkout-steps"><span class="checkout-step active">01 · Pedido</span><span class="checkout-step ${payment?'active':''}">02 · PIX</span><span class="checkout-step">03 · Entrega</span></nav>${body}</main>`}
function itemRow(item,index){return `<article class="checkout-item"><div class="checkout-item-img">${item.image_url?`<img src="${esc(item.image_url)}" alt="" style="width:100%;height:100%;object-fit:cover">`:'◈'}</div><div><div class="checkout-item-name">${esc(item.name)}</div><span class="checkout-item-meta">${Number(item.quantity)||1} unidade(s) · ${esc(item.delivery_type||'digital')}</span></div><div><strong>${money(Number(item.price)*Number(item.quantity))}</strong><br><button class="checkout-remove" data-remove="${index}">Remover</button></div></article>`}
function formView(total){if(!session)return `<div class="checkout-summary"><div class="checkout-alert">🔐 Entre na sua conta para continuar. Seu carrinho ficará salvo.</div><a class="checkout-generate" style="display:block;text-align:center;text-decoration:none" href="/#/login">Entrar na conta</a></div>`;const display=session.user.user_metadata?.display_name||'';return `<div class="checkout-summary"><div class="checkout-input"><label>Nome do pagador</label><input id="payerName" maxlength="120" value="${esc(display)}" placeholder="Seu nome completo"></div><div class="checkout-input"><label>CPF <span>· obrigatório para o PIX</span></label><input id="cpf" inputmode="numeric" maxlength="14" placeholder="000.000.000-00"></div><div class="checkout-total"><span>Total do pedido</span><strong>${money(total)}</strong></div><label class="checkout-terms"><input id="terms" type="checkbox"><span>Concordo com os <a href="/#/termos">Termos de Uso</a> e a <a href="/#/reembolso">Política de Reembolso</a>.</span></label><button id="generate" class="checkout-generate" ${cart.length?'':'disabled'}>Gerar pagamento PIX</button><div id="err" class="checkout-alert" style="display:none"></div><div class="checkout-safe"><div>✓ Dados protegidos e vinculados ao seu pedido</div><div>✓ PIX com confirmação automática</div><div>✓ Acompanhamento em tempo real</div></div></div>`}
function paymentView(p){const status=String(p.status||'pending').toLowerCase();const confirmed=['paid','processing','completed','delivered'].includes(status);const qr=p.qrCodeBase64?(String(p.qrCodeBase64).startsWith('data:')?p.qrCodeBase64:`data:image/png;base64,${p.qrCodeBase64}`):p.qrcodeUrl;return `<div class="pix-result"><div class="pix-state"><span>●</span><div><b>${confirmed?'Pagamento confirmado':'Aguardando pagamento'}</b><span>Pedido ${esc(String(p.orderId||'').slice(0,8))} · acompanhe o status abaixo.</span></div></div>${qr?`<img src="${esc(qr)}" alt="QR Code PIX">`:''}${p.copyPaste?`<div style="text-align:left"><small>PIX copia e cola</small><div class="pix-copy"><input id="copycode" readonly value="${esc(p.copyPaste)}"><button id="copy">Copiar</button></div></div>`:''}<div class="payment-timeline"><div class="on">✓ PIX gerado</div><div class="${confirmed?'on':''}">○ Pagamento confirmado</div><div class="${['completed','delivered'].includes(status)?'on':''}">○ Pedido processado e entregue</div></div><div id="payment-status" class="checkout-alert">Status atual: ${esc(p.status||'PENDENTE')}</div><a href="/orders.html" style="display:block;margin-top:14px;font-weight:800">Acompanhar em Meus pedidos →</a></div>`}
function render(){const total=cart.reduce((sum,item)=>sum+Number(item.price||0)*Number(item.quantity||1),0);const items=cart.map(itemRow).join('');app.innerHTML=shell(`<div class="checkout-grid-pro"><section class="checkout-card"><div class="checkout-card-head"><h2>Seu pedido</h2><p>${cart.length} item(ns) selecionado(s)</p></div>${items||'<div class="checkout-alert" style="margin:22px">Seu carrinho está vazio. <a href="/#/catalogo">Voltar ao catálogo</a></div>'}<div class="checkout-safe" style="margin:0 22px 22px"><div>✓ Compra protegida</div><div>✓ Produto digital entregue conforme o pedido</div><div>✓ Suporte disponível após a compra</div></div></section><aside class="checkout-card">${payment?paymentView(payment):formView(total)}</aside></div>`);document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{cart.splice(Number(btn.dataset.remove),1);saveCart();render()});document.querySelector('#generate')?.addEventListener('click',generate);document.querySelector('#copy')?.addEventListener('click',copyPix)}
async function errorText(error){try{const r=error?.context;if(r?.json){const b=await r.json();return b?.gateway_message||b?.message||b?.error||JSON.stringify(b)}if(r?.text)return await r.text()}catch{}return error?.message||'Não foi possível processar o pagamento.'}
async function generate(){if(busy||!sb)return;const err=document.querySelector('#err');err.style.display='block';err.textContent='Validando dados e gerando seu PIX…';const name=document.querySelector('#payerName')?.value.trim();const cpf=document.querySelector('#cpf')?.value.replace(/\D/g,'');if(!name){err.textContent='Informe o nome do pagador.';return}if(!validCpf(cpf)){err.textContent='Informe um CPF válido.';return}if(!document.querySelector('#terms')?.checked){err.textContent='Aceite os termos para continuar.';return}busy=true;const button=document.querySelector('#generate');if(button){button.disabled=true;button.textContent='Gerando PIX…'}try{const {data,error}=await sb.functions.invoke('rooblox-checkout-v2',{body:{items:cart,payerName:name,payerDocument:cpf}});if(error)throw error;if(data?.error)throw new Error(data.gateway_message||data.message||String(data.error));if(!data?.orderId)throw new Error('O pedido não foi criado. Tente novamente.');payment=data;sessionStorage.setItem('rooblox_checkout_payment',JSON.stringify(payment));render();watchStatus()}catch(error){busy=false;err.textContent=await errorText(error);if(button){button.disabled=false;button.textContent='Gerar pagamento PIX'}}}
async function watchStatus(){if(timer)clearInterval(timer);if(!payment?.orderId||!sb)return;const check=async()=>{const {data}=await sb.from('store_orders').select('id,status,updated_at').eq('id',payment.orderId).maybeSingle();if(!data)return;payment.status=data.status;const status=String(data.status).toLowerCase();if(['paid','processing','completed','delivered'].includes(status)){if(timer)clearInterval(timer);localStorage.removeItem('rooblox_cart');sessionStorage.removeItem('rooblox_checkout_payment');setTimeout(()=>location.href='/orders.html',1800)}else{const el=document.querySelector('#payment-status');if(el)el.textContent='Status atual: '+data.status}};await check();timer=setInterval(check,4000)}
async function copyPix(){const input=document.querySelector('#copycode');if(!input)return;try{await navigator.clipboard.writeText(input.value)}catch{input.select();document.execCommand('copy')}const button=document.querySelector('#copy');if(button){button.textContent='Copiado ✓';setTimeout(()=>button.textContent='Copiar',1500)}}
(async()=>{if(!sb){app.innerHTML=shell('<div class="checkout-alert">Supabase não configurado. Verifique as variáveis de ambiente.</div>');return}const result=await sb.auth.getSession();session=result.data.session;render();if(payment)watchStatus()})();