import { createClient } from '@supabase/supabase-js';
import './style.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,sb=url&&key?createClient(url,key):null;
const S={user:null,profile:null,cats:[],products:[],q:'',cat:'',cart:JSON.parse(localStorage.getItem('rooblox_cart')||'[]')};
const logo='<img class="logo" src="/logo.svg" alt="Rooblox">';
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const save=()=>localStorage.setItem('rooblox_cart',JSON.stringify(S.cart));
const toast=(m,e=false)=>{let x=document.createElement('div');x.className='toast '+(e?'error':'');x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2600)};
async function load(){if(sb){let {data:{session}}=await sb.auth.getSession();S.user=session?.user||null;if(S.user){let p=await sb.from('profiles').select('*').eq('id',S.user.id).maybeSingle();S.profile=p.data}let c=await sb.from('store_categories').select('*').eq('active',true).order('sort_order');S.cats=c.data||[];let p=await sb.from('products').select('id,name,description,price,image_url,featured,compare_at_price,badge,sort_order,category_slug,stock_quantity,delivery_type').eq('active',true).order('featured',{ascending:false}).order('sort_order');S.products=p.data||[]}render()}
function shell(body){return `<header><div class="nav"><a href="#/" class="brand">${logo}</a><nav><a href="#/">Início</a><a href="#/catalogo">Produtos</a><a href="#/ajuda">Ajuda</a></nav><div class="right"><label class="search"><span>⌕</span><input id="q" value="${esc(S.q)}" placeholder="Buscar produtos..."></label><a class="cart" href="#/checkout">Carrinho <b>${S.cart.length}</b></a>${S.user?`<a href="#/conta" class="account">${esc(S.profile?.display_name||S.profile?.username||'Minha conta')}</a>`:'<a href="#/login" class="primary small">Entrar</a>'}</div></div></header><main>${body}</main><footer><div>${logo}<p>Marketplace independente de produtos para jogos.</p></div><div><strong>Informações</strong><a href="#/termos">Termos de Uso</a><a href="#/privacidade">Privacidade</a><a href="#/reembolso">Reembolso</a><a href="#/ajuda">Ajuda</a></div><div><strong>Conta</strong><a href="#/conta">Minha conta</a><a href="#/pedidos">Meus pedidos</a></div><small>© 2026 Rooblox. Todos os direitos reservados.</small></footer>`}
function cards(a){return a.length?a.map(p=>`<article class="card"><a class="cover" href="#/produto/${p.id}">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<span>${esc(p.name[0]||'R')}</span>`}${p.badge?`<i>${esc(p.badge)}</i>`:''}</a><div><small>${esc(p.category_slug||'Produto')}</small><h3>${esc(p.name)}</h3><div class="price">${brl(p.price)} ${p.compare_at_price?`<del>${brl(p.compare_at_price)}</del>`:''}</div><button data-add="${p.id}" class="add">Adicionar ao carrinho</button></div></article>`).join(''):'<div class="empty"><h3>Nenhum produto encontrado</h3><p>Os produtos aparecerão aqui quando forem cadastrados.</p></div>'}
function home(){return `<section class="hero"><div><span class="eyebrow">MARKETPLACE ROOBLOX</span><h1>Seus itens favoritos.<br><em>Uma experiência melhor.</em></h1><p>Compre itens para seus jogos em uma plataforma moderna, rápida e feita para celular e computador.</p><a class="primary" href="#/catalogo">Explorar produtos</a></div><div class="hero-logo">${logo}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow dark">EXPLORE</span><h2>Categorias</h2></div><a href="#/catalogo">Ver catálogo →</a></div><div class="cats">${S.cats.map(c=>`<button data-cat="${esc(c.slug)}"><strong>${esc(c.name)}</strong><small>${esc(c.description)}</small></button>`).join('')}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow dark">DESTAQUES</span><h2>Produtos em destaque</h2></div></div><div class="grid">${cards(S.products.filter(p=>p.featured).slice(0,8))}</div></section><section class="trust"><div><b>Compra simples</b><span>Checkout rápido e organizado.</span></div><div><b>PIX</b><span>Pagamento processado pela MisticPay.</span></div><div><b>Suporte</b><span>Ajuda e acompanhamento do pedido.</span></div></section>`}
function catalog(){let a=S.products.filter(p=>(!S.cat||p.category_slug===S.cat)&&(!S.q||(`${p.name} ${p.description}`).toLowerCase().includes(S.q.toLowerCase())));return `<section class="page"><div class="page-head"><div><span class="eyebrow dark">CATÁLOGO</span><h1>Produtos</h1></div><span>${a.length} resultado(s)</span></div><div class="filters"><button data-cat="" class="${!S.cat?'active':''}">Todos</button>${S.cats.map(c=>`<button data-cat="${esc(c.slug)}" class="${S.cat===c.slug?'active':''}">${esc(c.name)}</button>`).join('')}</div><div class="grid">${cards(a)}</div></section>`}
function product(id){let p=S.products.find(x=>x.id===id);return `<section class="page">${p?`<a href="#/catalogo">← Voltar</a><div class="product"><div class="product-image">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<span>${esc(p.name[0])}</span>`}</div><div><span class="eyebrow dark">${esc(p.category_slug||'PRODUTO')}</span><h1>${esc(p.name)}</h1><p class="lead">${esc(p.description)}</p><div class="big-price">${brl(p.price)}</div><p>${p.stock_quantity>0?`${p.stock_quantity} unidade(s) disponíveis`:'Disponibilidade sob consulta'}</p><button data-add="${p.id}" class="primary wide">Adicionar ao carrinho</button></div></div>`:'<div class="empty">Produto não encontrado.</div>'}</section>`}
function auth(reg){return `<section class="auth"><div class="auth-card">${logo}<span class="eyebrow dark">${reg?'CRIAR CONTA':'ENTRAR'}</span><h1>${reg?'Crie sua conta':'Bem-vindo de volta'}</h1><form id="auth">${reg?'<label>Nome de usuário<input name="username" minlength="3" maxlength="24" required></label>':''}<label>E-mail<input name="email" type="email" required></label><label>Senha<input name="password" type="password" minlength="6" required></label>${reg?'<label class="check"><input type="checkbox" required> Aceito os <a href="#/termos">Termos de Uso</a>.</label>':''}<button class="primary wide">${reg?'Criar conta':'Entrar'}</button></form><p>${reg?'Já possui conta?':'Ainda não possui conta?'} <a href="#/${reg?'login':'cadastro'}">${reg?'Entrar':'Criar conta'}</a></p></div></section>`}
function checkout(){let total=S.cart.reduce((n,x)=>n+x.price*x.quantity,0);return `<section class="page"><div class="page-head"><div><span class="eyebrow dark">CHECKOUT</span><h1>Finalizar compra</h1></div></div><div class="checkout"><div class="panel"><h3>Seu carrinho</h3>${S.cart.length?S.cart.map(x=>`<div class="line"><span>${esc(x.name)} × ${x.quantity}</span><b>${brl(x.price*x.quantity)}</b></div>`).join(''):'<p>Seu carrinho está vazio.</p>'}</div><div class="panel"><h3>Pagamento</h3><div class="total"><span>Total</span><b>${brl(total)}</b></div><button id="pay" class="primary wide" ${!S.user||!S.cart.length?'disabled':''}>Pagar com PIX</button>${!S.user?'<p>Entre na sua conta para continuar.</p>':''}<div id="payment"></div></div></div></section>`}
function account(){if(!S.user)return auth(false);return `<section class="page"><div class="profile"><div class="avatar">${esc((S.profile?.display_name||S.user.email||'R')[0].toUpperCase())}</div><div><span class="eyebrow dark">MINHA CONTA</span><h1>${esc(S.profile?.display_name||S.profile?.username||'Minha conta')}</h1><p>${esc(S.user.email)}</p></div></div><div class="account-grid"><a class="panel" href="#/pedidos"><b>Meus pedidos</b><span>Acompanhe compras e entregas.</span></a><a class="panel" href="#/catalogo"><b>Continuar comprando</b><span>Voltar ao catálogo.</span></a><button id="logout" class="panel"><b>Sair</b><span>Encerrar sessão.</span></button></div></section>`}
function page(r){let t={termos:'Termos de Uso',privacidade:'Política de Privacidade',reembolso:'Política de Reembolso'}[r];return `<section class="page document"><span class="eyebrow dark">ROOBLOX</span><h1>${t}</h1><div class="panel"><h3>${t}</h3><p>Esta página será gerenciada pelo painel administrativo. O Rooblox poderá atualizar regras, políticas e informações para manter a plataforma clara e segura.</p><p>Em caso de dúvidas sobre uma compra, utilize a Central de Ajuda e informe o número do pedido.</p></div></section>`}
function help(){return `<section class="page"><div class="page-head"><div><span class="eyebrow dark">SUPORTE</span><h1>Central de Ajuda</h1></div></div><div class="help"><div class="panel"><h3>Pagamento</h3><p>O checkout utiliza PIX e a confirmação será processada pelo gateway.</p></div><div class="panel"><h3>Pedidos</h3><p>Consulte o histórico na sua conta para acompanhar o status.</p></div><div class="panel"><h3>Entrega</h3><p>O tipo de entrega aparece no produto e no pedido.</p></div><div class="panel"><h3>Atendimento</h3><p>Abra um ticket quando precisar de suporte.</p></div></div></section>`}
function orders(){return S.user?`<section class="page"><span class="eyebrow dark">HISTÓRICO</span><h1>Meus pedidos</h1><div id="orders" class="empty">Carregando...</div></section>`:auth(false)}
function admin(){return `<section class="page"><span class="eyebrow dark">ADMINISTRAÇÃO</span><h1>Painel Rooblox</h1><div class="admin-grid"><div class="panel"><b>${S.products.length}</b><span>Produtos ativos</span></div><div class="panel"><b>${S.cats.length}</b><span>Categorias</span></div><div class="panel"><b>${S.cart.length}</b><span>Itens no carrinho</span></div></div><div class="panel"><h3>Gestão</h3><p>Produtos, categorias, pedidos, pagamentos, cupons, suporte, usuários, cargos, auditoria e configurações devem ser administrados através das políticas RLS do Supabase.</p></div></section>`}
function route(){let [r,id]=location.hash.slice(2).split('/');return r==='catalogo'?catalog():r==='produto'?product(id):r==='login'?auth(false):r==='cadastro'?auth(true):r==='checkout'?checkout():r==='conta'?account():r==='pedidos'?orders():r==='ajuda'?help():r==='admin'?admin():['termos','privacidade','reembolso'].includes(r)?page(r):home()}
function render(){document.querySelector('#app').innerHTML=shell(route());bind()}
function bind(){document.querySelector('#q')?.addEventListener('input',e=>{S.q=e.target.value;render()});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;location.hash='#/catalogo'});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{let p=S.products.find(x=>x.id===b.dataset.add),o=S.cart.find(x=>x.id===p.id);o?o.quantity++:S.cart.push({id:p.id,name:p.name,price:Number(p.price),quantity:1});save();toast('Produto adicionado ao carrinho');render()});document.querySelector('#auth')?.addEventListener('submit',submit);document.querySelector('#logout')?.addEventListener('click',async()=>{await sb.auth.signOut();S.user=null;render()});document.querySelector('#pay')?.addEventListener('click',()=>toast('Pagamento PIX será ativado após configurar a Edge Function da MisticPay.')) ;if(location.hash==='#/pedidos')loadOrders()}
async function submit(e){e.preventDefault();if(!sb)return toast('Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no Vercel.',true);let f=new FormData(e.currentTarget),reg=location.hash.includes('cadastro'),r=reg?await sb.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{username:f.get('username')}}}):await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(r.error)return toast(r.error.message,true);await load();location.hash='#/'}
async function loadOrders(){if(!sb||!S.user)return;let {data}=await sb.from('orders').select('id,amount,status,created_at').eq('user_id',S.user.id).order('created_at',{ascending:false}),el=document.querySelector('#orders');if(el)el.innerHTML=data?.length?data.map(o=>`<div class="order panel"><b>#${o.id.slice(0,8)}</b><span>${brl(o.amount)}</span><span>${esc(o.status)}</span></div>`).join(''):'<div class="empty">Você ainda não possui pedidos.</div>'}
window.addEventListener('hashchange',render);load();
