export function rewardsPage(S,sb,esc,icons){
 const loading='<section class="page rewards-page"><div class="rewards-loading panel">'+icons.box+'<h2>Carregando recompensas...</h2></div></section>';
 if(!S.user)return '<section class="page rewards-page"><div class="rewards-hero"><div><span class="eyebrow dark">RECOMPENSAS</span><h1>Campanhas e benefícios</h1><p>Entre na sua conta para participar e acompanhar suas solicitações.</p><a class="primary" href="#/login">Entrar na conta</a></div></div></section>';
 setTimeout(()=>loadRewards(S,sb,esc,icons),0); return loading;
}
function rewardOpenKey(userId,campaignId){return 'rooblox:reward-opened:'+String(userId)+':'+String(campaignId)}
function getSavedOpen(userId,campaignId){try{const raw=localStorage.getItem(rewardOpenKey(userId,campaignId));if(!raw)return '';const parsed=JSON.parse(raw);if(!parsed?.opened_at)return '';return String(parsed.opened_at)}catch{return ''}}
function saveOpen(userId,campaignId,openedAt){try{localStorage.setItem(rewardOpenKey(userId,campaignId),JSON.stringify({opened_at:openedAt}))}catch{}}
async function loadRewards(S,sb,esc,icons){
 const root=document.querySelector('.rewards-page');if(!root||!sb)return;
 const {data:campaigns,error}=await sb.from('reward_campaigns').select('id,title,description,reward_robux,campaign_url,max_claims,created_at').eq('active',true).order('created_at',{ascending:false});
 if(error){root.innerHTML='<div class="panel rewards-error"><h2>Não foi possível carregar as recompensas</h2><p>'+esc(error.message||'Erro ao consultar as campanhas.')+'</p><button class="secondary" id="retry-rewards">Tentar novamente</button></div>';root.querySelector('#retry-rewards')?.addEventListener('click',()=>loadRewards(S,sb,esc,icons));return;}
 const ids=(campaigns||[]).map(c=>c.id);let claims=[];
 if(ids.length){const r=await sb.from('reward_claims').select('id,campaign_id,status,participant_name,campaign_opened_at,confirmed_at,created_at,updated_at').eq('user_id',S.user.id).in('campaign_id',ids);if(!r.error)claims=r.data||[];}
 const claimBy=new Map(claims.map(c=>[c.campaign_id,c]));
 root.innerHTML='<div class="rewards-hero"><div><span class="eyebrow dark">ÁREA DE RECOMPENSAS</span><h1>Recompensas</h1><p>Abra a campanha, confirme que acessou, informe o nome para análise e acompanhe tudo por aqui.</p></div></div><div class="rewards-list">'+(campaigns?.length?campaigns.map(c=>campaignCard(c,claimBy.get(c.id),S,esc,icons)).join(''):'<div class="panel rewards-empty"><div class="empty-icon">'+icons.box+'</div><h2>Nenhuma campanha disponível</h2><p>Quando houver uma campanha ativa, ela aparecerá aqui.</p></div>')+'</div>';
 root.querySelectorAll('[data-open-campaign]').forEach(a=>a.addEventListener('click',()=>{const card=a.closest('[data-campaign-card]');const openedAt=new Date().toISOString();const opened=card?.querySelector('[data-opened]');if(opened)opened.value=openedAt;saveOpen(S.user.id,a.dataset.openCampaign,openedAt);const b=card?.querySelector('[data-confirm-access]');if(b)b.disabled=false;const n=card?.querySelector('.campaign-confirm-note');if(n)n.textContent='Campanha aberta. Você pode voltar ao site quando terminar e confirmar o acesso.';}));
 root.querySelectorAll('[data-confirm-access]').forEach(b=>b.addEventListener('click',()=>{const card=b.closest('[data-campaign-card]');const name=String(card?.querySelector('[data-participant-name]')?.value||'').trim();const opened=card?.querySelector('[data-opened]')?.value;if(name.length<3||name.length>80){toastReward('Informe um nome entre 3 e 80 caracteres.',true);return;}if(!opened){toastReward('Abra a campanha primeiro.',true);return;}card.querySelector('[data-confirmed]').value=new Date().toISOString();b.disabled=true;b.textContent='Acesso confirmado ✓';const send=card.querySelector('[data-claim]');if(send)send.disabled=false;const n=card.querySelector('.campaign-confirm-note');if(n)n.textContent='Acesso confirmado. Sua solicitação está pronta para análise.';}));
 root.querySelectorAll('[data-claim]').forEach(b=>b.addEventListener('click',()=>claimReward(b.dataset.claim,S,sb,esc,icons)));
}
function campaignCard(c,claim,S,esc,icons){
 const labels={pending:['Pendente','Sua solicitação foi registrada e aguarda análise.'],review:['Em análise','A equipe está verificando sua participação.'],approved:['Aprovada','Sua recompensa foi aprovada.'],rejected:['Recusada','Esta solicitação não foi aprovada.']};
 let action;
 if(claim){const st=labels[claim.status]||['Registrada','Solicitação registrada.'];action='<div class="reward-status '+esc(claim.status)+'"><b>'+esc(st[0])+'</b><span>'+esc(st[1])+'</span>'+(claim.participant_name?'<small>Nome informado: '+esc(claim.participant_name)+'</small>':'')+'</div>'}
 else {const savedOpen=getSavedOpen(S.user.id,c.id);action='<div class="claim-flow"><label>Nome para análise<input data-participant-name maxlength="80" autocomplete="name" placeholder="Seu nome ou nome de usuário"></label><input type="hidden" data-opened value="'+esc(savedOpen)+'"><input type="hidden" data-confirmed><p class="campaign-confirm-note">'+(savedOpen?'Campanha já aberta. Você pode confirmar o acesso agora.':'Abra a campanha primeiro. Depois confirme que acessou para liberar o envio.')+'</p><div class="reward-actions">'+(c.campaign_url?'<a class="ghost" data-open-campaign="'+esc(c.id)+'" href="'+esc(c.campaign_url)+'" target="_blank" rel="noopener noreferrer">'+icons.arrow+'<span>Abrir campanha</span></a>':'<span class="reward-note">O administrador ainda não configurou o link da campanha.</span>')+'<button class="secondary" data-confirm-access '+(savedOpen?'':'disabled')+'>Confirmar que acessei</button><button class="primary reward-action" data-claim="'+esc(c.id)+'" disabled>Enviar para análise</button></div></div>'}
 return '<article class="panel reward-card" data-campaign-card="'+esc(c.id)+'"><div class="reward-card-top"><div class="reward-icon">'+(icons.gift||icons.box)+'</div><div><span class="eyebrow dark">CAMPANHA ATIVA</span><h2>'+esc(c.title)+'</h2></div><div class="reward-value"><b>'+Number(c.reward_robux||0).toLocaleString('pt-BR')+'</b><span>Robux</span></div></div><p>'+esc(c.description)+'</p><div class="reward-steps"><div><b>01</b><span>Abra a campanha</span></div><div><b>02</b><span>Informe seu nome e confirme o acesso</span></div><div><b>03</b><span>Envie para análise</span></div></div>'+action+'<small class="reward-note">A recompensa depende das regras e da validação. Não crie contas duplicadas nem tente burlar limites.</small></article>';
}
async function claimReward(id,S,sb,esc,icons){
 if(!S.user)return location.hash='#/login';const b=document.querySelector('[data-claim="'+CSS.escape(id)+'"]');if(!b)return;b.disabled=true;const card=b.closest('[data-campaign-card]');const name=String(card?.querySelector('[data-participant-name]')?.value||'').trim();const opened=card?.querySelector('[data-opened]')?.value;const confirmed=card?.querySelector('[data-confirmed]')?.value;
 if(name.length<3||name.length>80||!opened||!confirmed){b.disabled=false;toastReward('Informe seu nome e confirme o acesso antes de enviar.',true);return;}
 const {error}=await sb.from('reward_claims').insert({campaign_id:id,user_id:S.user.id,status:'pending',participant_name:name,campaign_opened_at:opened,confirmed_at:confirmed}).select('id,status').single();
 if(error){b.disabled=false;toastReward(error.code==='23505'?'Você já enviou uma solicitação para esta campanha.':error.message||'Não foi possível registrar a solicitação.',true);loadRewards(S,sb,esc,icons);return;}
 try{localStorage.removeItem(rewardOpenKey(S.user.id,id))}catch{}
 toastReward('Solicitação enviada para análise.');loadRewards(S,sb,esc,icons);
}
function toastReward(message,error=false){const x=document.createElement('div');x.className='toast '+(error?'error':'');x.innerHTML='<span>'+String(message).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))+'</span>';document.body.append(x);setTimeout(()=>x.remove(),3200)}