import { createClient } from '@supabase/supabase-js';
import './sitewide.css';
const url=String(import.meta.env.VITE_SUPABASE_URL||'').trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');
const key=String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'').trim();
const sb=url&&key?createClient(url,key):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function announcement(){if(!sb||document.querySelector('.rx-site-announcement'))return;const r=await sb.from('site_announcements').select('id,title,body,kind').eq('active',true).lte('starts_at',new Date().toISOString()).or('ends_at.is.null,ends_at.gt.'+new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(r.error||!r.data)return;const d=document.createElement('div');d.className='rx-site-announcement';d.innerHTML='<span><b>'+esc(r.data.title)+'</b> · '+esc(r.data.body)+'</span><button aria-label="Fechar">×</button>';d.querySelector('button').onclick=()=>{d.remove();sessionStorage.setItem('rx_notice_'+r.data.id,'1')};if(!sessionStorage.getItem('rx_notice_'+r.data.id))document.body.prepend(d)}
function progress(){const p=document.createElement('div');p.className='rx-progress';document.body.append(p);const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;p.style.width=(h>0?Math.min(100,scrollY/h*100):0)+'%'};addEventListener('scroll',update,{passive:true});update()}
function topButton(){const b=document.createElement('button');b.className='rx-top';b.textContent='↑';b.setAttribute('aria-label','Voltar ao topo');document.body.append(b);addEventListener('scroll',()=>b.classList.toggle('show',scrollY>500),{passive:true});b.onclick=()=>scrollTo({top:0,behavior:'smooth'})}
function mobileNav(){if(document.querySelector('.rx-mobile-nav'))return;const n=document.createElement('nav');n.className='rx-mobile-nav';n.innerHTML='<a href="#/" data-rx-route="#/">⌂<span>Início</span></a><a href="#/catalogo" data-rx-route="#/catalogo">⌕<span>Produtos</span></a><a href="#/checkout" data-rx-route="#/checkout">🛒<span>Carrinho</span></a><a href="#/conta" data-rx-route="#/conta">●<span>Conta</span></a>';document.body.append(n);const sync=()=>n.querySelectorAll('[data-rx-route]').forEach(a=>a.classList.toggle('active',location.hash===a.dataset.rxRoute||(a.dataset.rxRoute==='#/'&&(!location.hash||location.hash==='#/'))));addEventListener('hashchange',sync);sync()}
function shortcuts(){addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea|select/i.test(document.activeElement?.tagName||'')){e.preventDefault();document.querySelector('.search input,#q')?.focus()}if(e.key==='Escape')document.querySelector('.search input,#q')?.blur()})}
announcement();progress();topButton();mobileNav();shortcuts();