import { createClient } from '@supabase/supabase-js';
import './sitewide.css';
const url=String(import.meta.env.VITE_SUPABASE_URL||'').trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');
const key=String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'').trim();
const sb=url&&key?createClient(url,key):null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg=(d)=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
async function announcement(){if(!sb||document.querySelector('.rx-site-announcement'))return;const r=await sb.from('site_announcements').select('id,title,body,kind').eq('active',true).lte('starts_at',new Date().toISOString()).or('ends_at.is.null,ends_at.gt.'+new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(r.error||!r.data)return;const d=document.createElement('div');d.className='rx-site-announcement';d.innerHTML='<span><b>'+esc(r.data.title)+'</b> · '+esc(r.data.body)+'</span><button aria-label="Fechar">×</button>';d.querySelector('button').onclick=()=>{d.remove();sessionStorage.setItem('rx_notice_'+r.data.id,'1')};if(!sessionStorage.getItem('rx_notice_'+r.data.id))document.body.prepend(d)}
function progress(){const p=document.createElement('div');p.className='rx-progress';document.body.append(p);const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;p.style.width=(h>0?Math.min(100,scrollY/h*100):0)+'%'};addEventListener('scroll',update,{passive:true});update()}
function topButton(){const b=document.createElement('button');b.className='rx-top';b.textContent='↑';b.setAttribute('aria-label','Voltar ao topo');document.body.append(b);addEventListener('scroll',()=>b.classList.toggle('show',scrollY>500),{passive:true});b.onclick=()=>scrollTo({top:0,behavior:'smooth'})}
function mobileNav(){if(document.querySelector('.rx-mobile-nav'))return;const n=document.createElement('nav');n.className='rx-mobile-nav';n.innerHTML=`<a href="#/" data-rx-route="#/">${svg('<path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/>')}<span>Início</span></a><a href="#/catalogo" data-rx-route="#/catalogo">${svg('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>')}<span>Produtos</span></a><a href="#/checkout" data-rx-route="#/checkout">${svg('<path d="M3 5h2l2 11h10l3-8H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/>')}<span>Carrinho</span></a><a href="#/conta" data-rx-route="#/conta">${svg('<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>')}<span>Conta</span></a>`;document.body.append(n);const sync=()=>n.querySelectorAll('[data-rx-route]').forEach(a=>a.classList.toggle('active',location.hash===a.dataset.rxRoute||(a.dataset.rxRoute==='#/'&&(!location.hash||location.hash==='#/'))));addEventListener('hashchange',sync);sync()}
function shortcuts(){addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea|select/i.test(document.activeElement?.tagName||'')){e.preventDefault();document.querySelector('.search input,#q')?.focus()}if(e.key==='Escape')document.querySelector('.search input,#q')?.blur()})}
function pwa(){if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});}
announcement();progress();topButton();mobileNav();shortcuts();pwa();